config/routes.rb
Rails.application.routes.draw do

  resources :places

  resources :logs, only: [:edit, :update, :index, :show, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :index, :show]
  resources :clients, only: [:new, :create, :edit, :update, :index, :show]
  resource :user_sessions, only: [:new, :create, :destroy]
  
  get 'pages/about'

  get 'pages/contact'

  get 'signup' => 'users#new'
  
  get 'login' => 'user_sessions#new'

  post 'login' => 'user_sessions#create'

  delete 'logout' => 'user_sessions#destroy'

  root 'logs#root'

  get 'users/user_password/:id', to: 'users#password', as: 'password'

  get 'signin' => 'logs#signin'

  get 'signout' => 'logs#signout'

  post 'create_signin' => 'logs#create_signin'

  post 'create_signout' => 'logs#create_signout'

  get 'reports' => 'reports#select'

  post 'reports' => 'reports#generate'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	  after_initialize :defaults
  validates_format_of :mobile, with: /\A(\d{10}|[+. ]\d{11})\z/

  def defaults
    self.role = 'employee' if self.role.nil?
    self.active = 'active' if self.active.nil?
  end

  def admin?
  	self.role == 'admin'
  end

  def active?
    self.active.downcase == 'active'
  end
  
  has_many :logs
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_admin, only: [:new, :create, :edit, :update, :index, :show]
	before_action :set_user, only: [:edit, :update, :show, :password]
  before_action :require_user
  # GET /users/1
  def show
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.where("role = 'employee'")
    @users = @users.paginate(:page => params[:page], :per_page => 5)
  end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		respond_to do |format|
		if (User.where("email = :email" , { email: user_params[:email]}).count <= 0) && @user.save
      # Tell the UserMailer to send a welcome email after save
			format.html { redirect_to users_path , notice: 'User was successfully created.' }
			# UserMailer.welcome_email(@user).deliver
		else
			format.html { redirect_to users_path, :flash => { :error => "This email is already in use." }  }
			format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def edit
	end

	def password
	end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

	private
	def set_user
		if User.find_by id: params[:id]
			@user = User.find_by id: params[:id]
		else
			redirect_to users_path,notice:'User was not found.'
		end
	end

	def user_params
		params.require(:user).permit(:firstname, :middlename, :lastname, :email, :password, :mobile, :active)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this log from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class='col-sm-3'>
      <div class="form-group">
        <%= f.text_field :firstname, :placeholder => "First name", class: "form-control" %>
      </div>
      <div class="form-group">
       <%= f.text_field :middlename, :placeholder => "Middle name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :lastname, :placeholder => "Last name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.email_field :email, :placeholder => "Email", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.telephone_field :mobile, :placeholder => "Mobile", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, :placeholder => "Password", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save account", class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Update Employee Info</h3>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this log from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class='col-sm-3'>
      <div class="form-group">
        <%= f.text_field :firstname, :placeholder => "First name", class: "form-control" %>
      </div>
      <div class="form-group">
       <%= f.text_field :middlename, :placeholder => "Middle name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :lastname, :placeholder => "Last name", class: "form-control" %>
      </div>
      <div class="form-group">
       <%= f.email_field :email, :placeholder => "Email", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.telephone_field :mobile, :placeholder => "Mobile", class: "form-control" %>
      </div>
      <% if !@user.admin? %>
        <div class="form-group">
          <%= f.radio_button :active,  "active", :checked => @user.active? %>
          <%= label :active, "Active" %>
          <%= f.radio_button :active,  "inactive", :checked => !@user.active? %>
          <%= label :inctive, "Inactive" %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save changes", class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>


<%= link_to 'Back', users_path, class: "btn btn-link mclink"%>

app/views/users/index.html.erb
<h3>Employees</h3>

<div class="table-responsive">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th class="col-md-1">
          <div align="center">First Name</div>
        </th>
        <th class="col-md-1">
          <div align="center">Middle Name</div>
        </th>
        <th class="col-md-1">
          <div align="center">Last Name</div>
        </th>
        <th class="col-md-1">
          <div align="center">Email</div>
        </th>
        <th class="col-md-1">
          <div align="center">Mobile</div>
        </th>
        <th class="col-md-1">
          <div align="center">Status</div>
        </th>
        <th class="col-md-2">
          <div align="center">Actions </div>
        </th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <% if current_user.admin? %>
            <td class="col-md-1"><%= user.firstname%></td>
            <td class="col-md-1"><%= user.middlename %></td>
            <td class="col-md-1"><%= user.lastname%></td>
              <td class="col-md-1"><%= user.email %></td>
              <td class="col-md-1"><%= user.mobile %></td>
              <td class="col-md-1"><%= user.active %></td>
            <td class="col-md-2"><%= link_to 'Edit', edit_user_path(user), class: "btn btn-link mclink" %> <%= link_to 'New Password', password_path(user), class: "btn btn-link mclink" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @users, renderer: BootstrapPagination::Rails %>

<%= link_to 'New User', signup_path, class: "btn btn-link mclink" %>

app/views/users/new.html.erb
<h3>Add Employee</h3>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this log from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class='col-sm-3'>
      <div class="form-group">
        <%= f.text_field :firstname, :placeholder => "First name", class: "form-control" %>
      </div>
      <div class="form-group">
       <%= f.text_field :middlename, :placeholder => "Middle name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :lastname, :placeholder => "Last name", class: "form-control" %>
      </div>
      <div class="form-group">
       <%= f.email_field :email, :placeholder => "Email", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.telephone_field :mobile, :placeholder => "Mobile", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, :placeholder => "Password", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Create account", class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/password.html.erb
<h1>Editing User Password</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class='col-sm-3'>
      <div class="form-group">
        <%= f.password_field :password, :placeholder => "New Password", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save new Password", class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>


<%= link_to 'Show', @user,  class: "btn btn-link mclink"%> |
<%= link_to 'Back', users_path, class: "btn btn-link mclink"%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Middle Name:</strong>
  <%= @user.middlename %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-link mclink" %> |
<%= link_to 'Back', users_path, class: "btn btn-link mclink" %>