config/routes.rb
Rails.application.routes.draw do

  resources :places

  resources :logs, only: [:edit, :update, :index, :show, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :index, :show]
  resources :clients, only: [:new, :create, :edit, :update, :index, :show]
  resource :user_sessions, only: [:new, :create, :destroy]
  
  get 'pages/about'

  get 'pages/contact'

  get 'signup' => 'users#new'
  
  get 'login' => 'user_sessions#new'

  post 'login' => 'user_sessions#create'

  delete 'logout' => 'user_sessions#destroy'

  root 'logs#root'

  get 'users/user_password/:id', to: 'users#password', as: 'password'

  get 'signin' => 'logs#signin'

  get 'signout' => 'logs#signout'

  post 'create_signin' => 'logs#create_signin'

  post 'create_signout' => 'logs#create_signout'

  get 'reports' => 'reports#select'

  post 'reports' => 'reports#generate'

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :places
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update]
  before_action :require_admin

  def new
    @client = Client.new
  end

#   :create, :edit, :update, :index, :show
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end

  def index
    @clients = Client.all.order("Name Asc")
  end

  def show
  end

  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_path, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_client
    if Client.find_by id: params[:id]
      @client = Client.find_by id: params[:id]
    else
      redirect_to clients_path,notice:'Client was not found.'
    end

  end

# Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(:name)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class='col-sm-3'>
      <div class="form-group">
        <%= f.text_field :name, :placeholder => "Name", class: "form-control"  %>
      </div>
      <div class="form-group">
        <%= f.submit "Save Client", class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h3>Editing Client</h3>

<%= render 'form' %>

<%= link_to 'Back', places_path,  class: "btn btn-link mclink" %>

app/views/clients/index.html.erb
<h3>Clients</h3>

<% if @clients.present? %>
<div class="table-responsive">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th class="col-md-1">
          <div align="center">Name</div>
        </th>
        <th class="col-md-1">
          <div align="center">Actions</div>
        </th>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <% if current_user.admin? %>
            <td class="col-md-1"><%= client.name %></td>
            <td class="col-md-1"><%= link_to 'Edit', edit_client_path(client), class: "btn btn-link mclink" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<%= link_to 'New Client', new_client_path, class: "btn btn-link mclink" %>

app/views/clients/new.html.erb
<h3>New Client</h3>

<%= render 'form' %>

<%= link_to 'Back', places_path,  class: "btn btn-link mclink" %>

app/views/clients/show.html.erb
<div class="row">
  <div class='col-md-3'>
    <div class="form-group">
      <%= label_tag :Client %><br>
      <div class='input-group' id='place'>
        <%= @client.name %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_client_path(@client),  class: "btn btn-link mclink" %> |
<%= link_to 'Back', clients_path,  class: "btn btn-link mclink" %>