config/routes.rb
Rails.application.routes.draw do

  resources :places

  resources :logs, only: [:edit, :update, :index, :show, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :index, :show]
  resources :clients, only: [:new, :create, :edit, :update, :index, :show]
  resource :user_sessions, only: [:new, :create, :destroy]
  
  get 'pages/about'

  get 'pages/contact'

  get 'signup' => 'users#new'
  
  get 'login' => 'user_sessions#new'

  post 'login' => 'user_sessions#create'

  delete 'logout' => 'user_sessions#destroy'

  root 'logs#root'

  get 'users/user_password/:id', to: 'users#password', as: 'password'

  get 'signin' => 'logs#signin'

  get 'signout' => 'logs#signout'

  post 'create_signin' => 'logs#create_signin'

  post 'create_signout' => 'logs#create_signout'

  get 'reports' => 'reports#select'

  post 'reports' => 'reports#generate'

end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :logs
	belongs_to :client
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update]
  before_action :require_admin
  # GET /places
  # GET /places.json
  def index
    @places = Place.all.order("Name ASC")
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    @clients = Client.all
  end

  # GET /places/1/edit
  def edit
    @clients = Client.all
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to places_path, notice: 'Place was successfully created.' }
        format.json { render :index, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    @place.client_id = params[:place][:client_id]
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to places_path, notice: 'Place was successfully updated.' }
        format.json { render :index, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      if Place.find_by id: params[:id]
        @place = Place.find_by id: params[:id]
      else
        redirect_to places_path,notice:'Place was not found.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :client_id)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
      <div class='col-md-3'>
        <div class="form-group">
          <%= label_tag :title, :Client %><br>
          <div class='input-group' id='client'>
            <%= select("place", "client_id", @clients.collect {|p| [ p.name, p.id ] }, {}, class: "form-control")%>
          </div>
        </div>
      </div>
    </div>
  <div class="row">
    <div class='col-sm-3'>
      <div class="form-group">
        <%= f.text_field :name, :placeholder => "Name", class: "form-control"  %>
      </div>
      <div class="form-group">
        <%= f.submit "Save Place", class: "btn btn-danger" %>
      </div>
    </div>
  </div>
    <%= hidden_field_tag "id",  @place.id  %>
<% end %>

app/views/places/edit.html.erb
<h3>Editing place</h3>

<%= render 'form' %>

<%= link_to 'Back', places_path,  class: "btn btn-link mclink" %>

app/views/places/index.html.erb
<h3>Places</h3>

<div class="table-responsive">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th class="col-md-1">
          <div align="center">Name</div>
        </th>
        <th class="col-md-1">
          <div align="center">Client</div>
        </th>
        <th class="col-md-1">
          <div align="center">Actions</div>
        </th>
    </thead>
    <tbody>
      <% @places.each do |place| %>
        <tr>
          <% if current_user.admin? %>
              <td class="col-md-1"><%= place.name %></td>
              <td class="col-md-1"><%= place.client.name %></td>
            <td class="col-md-1"><%= link_to 'Edit', edit_place_path(place), class: "btn btn-link mclink" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New Place', new_place_path, class: "btn btn-link mclink" %>

app/views/places/new.html.erb
<h3>New Place</h3>

<%= render 'form' %>

<%= link_to 'Back', places_path,  class: "btn btn-link mclink" %>

app/views/places/show.html.erb
<div class="row">
  <div class='col-md-3'>
    <div class="form-group">
      <%= label_tag :Name %><br>
      <div class='input-group' id='place'>
        <%= @place.name %>
      </div>
    </div>
  </div>
  <div class='col-md-2'>
    <div class="form-group">
      <%= label_tag :Client %><br>
      <div class='input-group' id='place'>
        <%= @place.client.name %>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_place_path(@place),  class: "btn btn-link mclink" %> |
<%= link_to 'Back', places_path,  class: "btn btn-link mclink" %>