config/routes.rb
Rails.application.routes.draw do

  resources :places

  resources :logs, only: [:edit, :update, :index, :show, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :index, :show]
  resources :clients, only: [:new, :create, :edit, :update, :index, :show]
  resource :user_sessions, only: [:new, :create, :destroy]
  
  get 'pages/about'

  get 'pages/contact'

  get 'signup' => 'users#new'
  
  get 'login' => 'user_sessions#new'

  post 'login' => 'user_sessions#create'

  delete 'logout' => 'user_sessions#destroy'

  root 'logs#root'

  get 'users/user_password/:id', to: 'users#password', as: 'password'

  get 'signin' => 'logs#signin'

  get 'signout' => 'logs#signout'

  post 'create_signin' => 'logs#create_signin'

  post 'create_signout' => 'logs#create_signout'

  get 'reports' => 'reports#select'

  post 'reports' => 'reports#generate'

end

app/views/layouts/_footer.html.erb
<br/>
<p>Developed by Rafael Ferreira - Copyright 2016</p>

app/views/layouts/_header.html.erb
	<nav class="navbar navbar-default">
  <div class="container-fluid">
   <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag 'miguellogo.png', alt: "Logo", height: 30 %>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path  %></li>
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path%></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.firstname %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% if current_user.admin? %>
              <li><%= link_to "Add Employee", signup_path %></li>
              <li><%= link_to "List Employees", users_path %></li>
              <li><%= link_to "List Clients", clients_path %></li>
              <li><%= link_to "List Places", places_path %></li>
              <% end %>
              <li><%= link_to "Check Hours", logs_path %></li>
              <li><%= link_to "Hours Report", reports_path %></li>
              <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mcshifts</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
		<% if msg.is_a?(String) %>
			<div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<%= content_tag :div, msg, :id => "flash_#{name}" %>
			</div>
		<% end %>
	<% end %>		

 	
	<%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>